<?php
/**
 * KePHP, Keep PHP easy!
 */

namespace Demo\Controller;

use Ke\Utils\DocMen\DocController;
use Ke\Utils\DocMen\DocMen;

class Mydoc extends DocController
{


	protected function onConstruct()
	{
		$this->doc = DocMen::getInstance('docmen');
		parent::onConstruct(); // TODO: Change the autogenerated stub
	}

	public function index()
	{

	}

	public function show()
	{
		return parent::show();
	}
}